/**
 * coding-memory.ts — Cross-session coding memory for Tappi Coding Mode.
 *
 * Auto-logs structured session summaries to `.tappi-coding-memory/` in the project dir
 * at team dissolve. Future sessions bootstrap from these summaries so knowledge persists.
 *
 * Directory layout:
 *   .tappi-coding-memory/
 *     .gitignore          — ignores everything in this dir
 *     main.md             — project-level state (tech stack, decisions, session count)
 *     sessions/           — one file per team session
 *     decisions/          — manually logged decisions and notes
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Types ───

export interface TeammateMemory {
  name: string;
  role: string;
  status: string;
  result?: string;
  filesWritten?: string[];
  toolsUsed?: string[];
  error?: string;
}

export interface ContractMemory {
  path: string;
  description: string;
  phase: number;
}

export interface TeamSessionSummary {
  teamId: string;
  taskDescription: string;
  durationMs: number;
  createdAt: string;        // ISO timestamp of team creation
  dissolvedAt: string;      // ISO timestamp of dissolve
  teammates: TeammateMemory[];
  contracts: ContractMemory[];
  phasesCompleted: number;
  validationResults?: string;
  workingDir: string;
}

// ─── Path helpers ───

function resolveDir(projectDir: string): string {
  return projectDir.replace(/^~/, process.env.HOME || process.env.USERPROFILE || '.');
}

function memoryRoot(projectDir: string): string {
  return path.join(resolveDir(projectDir), '.tappi-coding-memory');
}

function sessionsDir(projectDir: string): string {
  return path.join(memoryRoot(projectDir), 'sessions');
}

function decisionsDir(projectDir: string): string {
  return path.join(memoryRoot(projectDir), 'decisions');
}

function mainMdPath(projectDir: string): string {
  return path.join(memoryRoot(projectDir), 'main.md');
}

// ─── Slugify helper ───

function slugify(text: string, maxLen = 50): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, maxLen)
    .replace(/-+$/, ''); // trim trailing dashes
}

// ─── Date helpers ───

function datestamp(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

function formatDuration(ms: number): string {
  const totalSec = Math.floor(ms / 1000);
  const min = Math.floor(totalSec / 60);
  const sec = totalSec % 60;
  return min > 0 ? `${min}m ${sec}s` : `${sec}s`;
}

// ─── Init ───

/**
 * Create `.tappi-coding-memory/` dir structure if it doesn't exist.
 * Idempotent — safe to call multiple times.
 */
export function initCodingMemory(projectDir: string): void {
  const root = memoryRoot(projectDir);
  const sessDir = sessionsDir(projectDir);
  const decDir = decisionsDir(projectDir);

  fs.mkdirSync(root, { recursive: true });
  fs.mkdirSync(sessDir, { recursive: true });
  fs.mkdirSync(decDir, { recursive: true });

  // Gitignore — keeps the memory dir out of the project's VCS
  const gitignorePath = path.join(root, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, '*\n', 'utf-8');
  }

  // Bootstrap main.md if it doesn't exist
  if (!fs.existsSync(mainMdPath(projectDir))) {
    const projectName = path.basename(resolveDir(projectDir));
    const initial = `# ${projectName} — Coding Memory\n\n` +
      `> Auto-generated by Tappi Coding Mode. Do not delete.\n\n` +
      `## Project\n- Name: ${projectName}\n- Dir: ${resolveDir(projectDir)}\n\n` +
      `## Sessions\n- Count: 0\n- Last activity: (none)\n\n` +
      `## Tech Stack\n- (update as discovered)\n\n` +
      `## Key Architectural Decisions\n- (recorded as sessions complete)\n`;
    fs.writeFileSync(mainMdPath(projectDir), initial, 'utf-8');
  }
}

// ─── Log session ───

/**
 * Write a structured markdown session log to `sessions/YYYY-MM-DD-<slug>.md`.
 */
export function logTeamSession(projectDir: string, summary: TeamSessionSummary): string {
  try {
    initCodingMemory(projectDir);

    const slug = slugify(summary.taskDescription);
    const filename = `${datestamp()}-${slug || summary.teamId}.md`;
    const filePath = path.join(sessionsDir(projectDir), filename);

    // Build human-readable markdown
    const lines: string[] = [];
    lines.push(`# Session: ${summary.taskDescription}`);
    lines.push('');
    lines.push(`**Team:** ${summary.teamId}  `);
    lines.push(`**Date:** ${summary.dissolvedAt}  `);
    lines.push(`**Duration:** ${formatDuration(summary.durationMs)}  `);
    lines.push(`**Phases:** ${summary.phasesCompleted}  `);
    lines.push(`**Dir:** ${summary.workingDir}  `);
    lines.push('');

    // Teammates
    lines.push('## Teammates');
    for (const tm of summary.teammates) {
      lines.push(`### ${tm.name} (${tm.role})`);
      lines.push(`- Status: ${tm.status}`);
      if (tm.filesWritten && tm.filesWritten.length > 0) {
        lines.push(`- Files: ${tm.filesWritten.join(', ')}`);
      }
      if (tm.toolsUsed && tm.toolsUsed.length > 0) {
        const uniq = [...new Set(tm.toolsUsed)];
        lines.push(`- Tools: ${uniq.join(', ')}`);
      }
      if (tm.result) {
        lines.push(`- Result: ${tm.result.slice(0, 300)}`);
      }
      if (tm.error) {
        lines.push(`- Error: ${tm.error}`);
      }
    }
    lines.push('');

    // Contracts
    if (summary.contracts.length > 0) {
      lines.push('## Contracts Written');
      for (const c of summary.contracts) {
        lines.push(`- \`${c.path}\` (phase ${c.phase}): ${c.description}`);
      }
      lines.push('');
    }

    // Files modified (aggregated)
    const allFiles = summary.teammates.flatMap(tm => tm.filesWritten || []);
    const uniqueFiles = [...new Set(allFiles)];
    if (uniqueFiles.length > 0) {
      lines.push('## Files Modified');
      for (const f of uniqueFiles) {
        lines.push(`- ${f}`);
      }
      lines.push('');
    }

    // Key decisions (extracted from task description + results)
    const decisions: string[] = [];
    // Extract any "decision" or "chose" patterns from results
    for (const tm of summary.teammates) {
      const resultText = tm.result || '';
      const decisionMatches = resultText.match(/(?:decided?|chose?|selected?|approach|pattern|architecture)[^.!?\n]{0,120}/gi);
      if (decisionMatches) {
        decisions.push(...decisionMatches.map(d => d.trim()));
      }
    }
    if (decisions.length > 0) {
      lines.push('## Key Decisions');
      for (const d of decisions.slice(0, 10)) {
        lines.push(`- ${d}`);
      }
      lines.push('');
    }

    // Validation results
    if (summary.validationResults) {
      lines.push('## Validation Results');
      lines.push(summary.validationResults.slice(0, 1000));
      lines.push('');
    }

    // Open issues
    const blockedTeammates = summary.teammates.filter(tm => tm.status === 'blocked' || tm.status === 'failed');
    if (blockedTeammates.length > 0) {
      lines.push('## Open Issues');
      for (const tm of blockedTeammates) {
        lines.push(`- ${tm.name}: ${tm.status}${tm.error ? ` — ${tm.error}` : ''}`);
      }
      lines.push('');
    }

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
    console.log(`[coding-memory] Session logged: ${filePath}`);
    return filePath;
  } catch (err: any) {
    console.error('[coding-memory] logTeamSession error:', err?.message);
    return '';
  }
}

// ─── Update main state ───

/**
 * Update `main.md` with new project-level state.
 * Appends an update block with the current timestamp.
 */
export function updateMainState(projectDir: string, updates: string): void {
  try {
    initCodingMemory(projectDir);
    const mdPath = mainMdPath(projectDir);

    // Count sessions for the session counter
    const sessDir = sessionsDir(projectDir);
    let sessionCount = 0;
    try {
      sessionCount = fs.readdirSync(sessDir).filter(f => f.endsWith('.md')).length;
    } catch {}

    // Read current main.md and update the session count + last activity
    let content = fs.existsSync(mdPath) ? fs.readFileSync(mdPath, 'utf-8') : '';

    // Update session count line
    content = content.replace(/- Count: \d+/, `- Count: ${sessionCount}`);
    // Update last activity line
    const now = new Date().toISOString();
    content = content.replace(/- Last activity: .*/, `- Last activity: ${now}`);

    // Append the update block
    content += `\n---\n_Updated: ${now}_\n\n${updates}\n`;

    fs.writeFileSync(mdPath, content, 'utf-8');
  } catch (err: any) {
    console.error('[coding-memory] updateMainState error:', err?.message);
  }
}

// ─── Bootstrap context ───

/**
 * Reads `main.md` + last 3 session logs.
 * Returns a ~400-600 token context string for the agent's system prompt.
 */
export function bootstrapContext(projectDir: string): string {
  const root = memoryRoot(projectDir);
  if (!fs.existsSync(root)) return '';

  const parts: string[] = [];
  parts.push('## Past Session Memory (.tappi-coding-memory)');
  parts.push('');

  // main.md
  const mdPath = mainMdPath(projectDir);
  if (fs.existsSync(mdPath)) {
    try {
      const mainContent = fs.readFileSync(mdPath, 'utf-8');
      // Cap main.md contribution at 800 chars
      const capped = mainContent.length > 800
        ? mainContent.slice(0, 800) + '\n... (truncated)'
        : mainContent;
      parts.push('### Project State (main.md)');
      parts.push(capped);
      parts.push('');
    } catch {}
  }

  // Last 3 session logs
  const sessDir = sessionsDir(projectDir);
  if (fs.existsSync(sessDir)) {
    try {
      const sessionFiles = fs.readdirSync(sessDir)
        .filter(f => f.endsWith('.md'))
        .sort()
        .reverse()
        .slice(0, 3);

      if (sessionFiles.length > 0) {
        parts.push('### Recent Sessions');
        for (const f of sessionFiles) {
          const filePath = path.join(sessDir, f);
          try {
            const content = fs.readFileSync(filePath, 'utf-8');
            // Cap each session at 400 chars
            const capped = content.length > 400
              ? content.slice(0, 400) + '\n... (truncated)'
              : content;
            parts.push(`#### ${f}`);
            parts.push(capped);
            parts.push('');
          } catch {}
        }
      }
    } catch {}
  }

  const result = parts.join('\n');

  // Hard cap at 2400 chars (~600 tokens)
  if (result.length > 2400) {
    return result.slice(0, 2400) + '\n... [coding memory truncated]';
  }
  return result;
}

// ─── Search memory ───

/**
 * Grep across all session logs + decisions for a query string.
 * Returns matching lines with file context.
 */
export function searchMemory(projectDir: string, query: string): string {
  const root = memoryRoot(projectDir);
  if (!fs.existsSync(root)) return '(no coding memory found)';

  const results: string[] = [];
  const lowerQuery = query.toLowerCase();

  function searchDir(dir: string, label: string): void {
    if (!fs.existsSync(dir)) return;
    const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));
    for (const f of files) {
      const filePath = path.join(dir, f);
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        const lines = content.split('\n');
        const matchingLines: string[] = [];
        for (let i = 0; i < lines.length; i++) {
          if (lines[i].toLowerCase().includes(lowerQuery)) {
            // Include one line of context around the match
            const from = Math.max(0, i - 1);
            const to = Math.min(lines.length - 1, i + 1);
            matchingLines.push(lines.slice(from, to + 1).join('\n'));
          }
        }
        if (matchingLines.length > 0) {
          results.push(`**${label}/${f}:**`);
          results.push(...matchingLines.slice(0, 5)); // max 5 matches per file
          results.push('');
        }
      } catch {}
    }
  }

  searchDir(sessionsDir(projectDir), 'sessions');
  searchDir(decisionsDir(projectDir), 'decisions');

  // Also search main.md
  const mdPath = mainMdPath(projectDir);
  if (fs.existsSync(mdPath)) {
    try {
      const content = fs.readFileSync(mdPath, 'utf-8');
      const lines = content.split('\n');
      const matchingLines: string[] = [];
      for (const line of lines) {
        if (line.toLowerCase().includes(lowerQuery)) {
          matchingLines.push(line);
        }
      }
      if (matchingLines.length > 0) {
        results.push('**main.md:**');
        results.push(...matchingLines.slice(0, 5));
        results.push('');
      }
    } catch {}
  }

  if (results.length === 0) {
    return `No matches found for "${query}" in coding memory.`;
  }

  return results.join('\n');
}

// ─── Manual decision logging ───

/**
 * Manually log a decision or note to the decisions/ directory.
 * `type`: 'decision' | 'note'
 */
export function logDecision(projectDir: string, content: string, type: 'decision' | 'note'): string {
  try {
    initCodingMemory(projectDir);
    const decDir = decisionsDir(projectDir);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `${timestamp}-${type}.md`;
    const filePath = path.join(decDir, filename);
    const markdown = `# ${type.charAt(0).toUpperCase() + type.slice(1)} — ${new Date().toISOString()}\n\n${content}\n`;
    fs.writeFileSync(filePath, markdown, 'utf-8');
    return `✓ ${type} logged to ${filePath}`;
  } catch (err: any) {
    return `❌ Failed to log ${type}: ${err?.message}`;
  }
}
